language: node_js
node_js:
  - node
  - 6.0
cache:
  directories:
    - $HOME/.npm
    - node_modules
    - examples/node_modules
before_install:
  - npm config set engine-strict true
install:
  - npm install
  - npm run test:examples