language: node_js
node_js:
  - node
  - 6.0
cache:
  directories:
    - $HOME/.npm
    - node_modules
    - examples/node_modules
before_install:
  - npm config set engine-strict true
install:
  - npm install
  - npm link --ignore-scripts
  - cd examples && npm link es6-lenses && npm i --ignore-scripts && npm test